#Version of the ROM
CARBON_CODENAME := R
CARBON_REVISION := CR-9.0

ifndef CARBON_BUILDTYPE
  CARBON_BUILDTYPE := UNOFFICIAL
endif

TARGET_PRODUCT_SHORT := $(TARGET_PRODUCT)
TARGET_PRODUCT_SHORT := $(subst carbon_,,$(TARGET_PRODUCT_SHORT))

ifeq ($(WITH_GMS),true)
CARBON_VERSION := $(CARBON_CODENAME)-$(TARGET_PRODUCT_SHORT)-$(shell date -u +%y%m%d)-GApps-$(CARBON_BUILDTYPE)
else
CARBON_VERSION := $(CARBON_CODENAME)-$(TARGET_PRODUCT_SHORT)-$(shell date -u +%y%m%d)-$(CARBON_BUILDTYPE)
endif

PRODUCT_BUILD_PROP_OVERRIDES += BUILD_DISPLAY_ID="$(BUILD_ID)-$(BUILD_USERNAME)@$(BUILD_HOSTNAME)"
